### ISSUE TITLE
Admin permission request for jupyterlab/jupyterlab

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/team-compass#185]
In https://github.com/jupyterlab/jupyterlab/pull/14069#issuecomment-1465700022, @jtpio suggested that I try cutting a release using the workflow. In [my releaser run](https://github.com/jupyterlab/jupyterlab/actions/runs/4410479714/jobs/7727991722), I was denied because I lacked admin permissions. See log excerpt below. 

Can I please have admin permissions to the jupyterlab/jupyterlab package so that I can cut a new alpha release? Thanks!

```
+ python -m jupyter_releaser.actions.prep_release
Getting GitHub connection for jupyterlab/jupyterlab
Getting permission level for JasonWeill
User JasonWeill does not have admin permission
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/jupyter_releaser/actions/prep_release.py", line 9, in <module>
    setup(False)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/jupyter_releaser/actions/common.py", line 19, in setup
    return prepare_environment(fetch_draft_release=fetch_draft_release)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/jupyter_releaser/util.py", line 615, in prepare_environment
    raise RuntimeError(
RuntimeError: Could not get user permission level, assuming user was not admin!
Prepare Environment
  Error: Process completed with exit code 1.
```

**Comment by jtpio** [comment]
@JasonWeill you should have Admin rights on `jupyterlab/jupyterlab` now.

**Comment by jtpio** [comment]
FYI I also made a quick edit to the `RELEASE.md` document: https://github.com/jupyterlab/jupyterlab/pull/14188

**Comment by jtpio** [comment]
For reference there is now a dedicated Release team under the `jupyterlab` organization with Admin access to some of the repos.

This could be useful for example if someone needs a release of JupyterLab, has a particular questions about a release or would like to be able to make releases as well. The team can be mentioned on GitHub with `@jupyterlab/release`.
